qingyin.legacy.keystore=../signing/qingyin-release-1.0.p12
qingyin.legacy.keystore.password=5676e9681f4269dcbe92d6a36ae4ff5afbf6a624cb31b505
qingyin.legacy.keystore.alias=qingyin
qingyin.legacy.key.password=5676e9681f4269dcbe92d6a36ae4ff5afbf6a624cb31b505
